# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class FullItem(scrapy.Item):
    first_name = scrapy.Field()
    last_name = scrapy.Field()
    full_name = scrapy.Field()
    state = scrapy.Field()
    city = scrapy.Field()
    speciality = scrapy.Field()
    plans = scrapy.Field()
    general_plan = scrapy.Field()
    url = scrapy.Field()
    spider_name = scrapy.Field()
    date = scrapy.Field()
    education = scrapy.Field()
    board_sertifications = scrapy.Field()
    conditions_treated = scrapy.Field()
    office_address = scrapy.Field()
    age = scrapy.Field()
    gender = scrapy.Field()
    midle_name = scrapy.Field()
    subspecialty = scrapy.Field()
    office_name = scrapy.Field()
    procedures = scrapy.Field()
    awards_and_recognition = scrapy.Field()
    memberships = scrapy.Field()
    languages_spoken = scrapy.Field()
    image_urls = scrapy.Field()
    bio = scrapy.Field()

class InsuranceItem(scrapy.Item):
    first_name = scrapy.Field()
    last_name = scrapy.Field()
    full_name = scrapy.Field()
    state = scrapy.Field()
    city = scrapy.Field()
    speciality = scrapy.Field()
    plans = scrapy.Field()
    general_plan = scrapy.Field()
    url = scrapy.Field()
    spider_name = scrapy.Field()
    date = scrapy.Field()


class HealthgradesItem(scrapy.Item):
    first_name = scrapy.Field()
    last_name = scrapy.Field()
    specialty = scrapy.Field()
    state = scrapy.Field()
    payor1 = scrapy.Field()
    payor2 = scrapy.Field()
    payor3 = scrapy.Field()
    payor4 = scrapy.Field()
    payor5 = scrapy.Field()
    payor6 = scrapy.Field()
    payor7 = scrapy.Field()
    payor8 = scrapy.Field()
    payor9 = scrapy.Field()
    payor10 = scrapy.Field()
    payor1_plan1 = scrapy.Field()
    payor1_plan2 = scrapy.Field()
    payor1_plan3 = scrapy.Field()
    payor1_plan4 = scrapy.Field()
    payor1_plan5 = scrapy.Field()
    payor2_plan5 = scrapy.Field()
    payor2_plan4 = scrapy.Field()
    payor2_plan3 = scrapy.Field()
    payor2_plan2 = scrapy.Field()
    payor2_plan1 = scrapy.Field()
    payor3_plan5 = scrapy.Field()
    payor3_plan4 = scrapy.Field()
    payor3_plan3 = scrapy.Field()
    payor3_plan2 = scrapy.Field()
    payor3_plan1 = scrapy.Field()
    payor4_plan5 = scrapy.Field()
    payor4_plan4 = scrapy.Field()
    payor4_plan3 = scrapy.Field()
    payor4_plan2 = scrapy.Field()
    payor4_plan1 = scrapy.Field()
    payor5_plan2 = scrapy.Field()
    payor5_plan3 = scrapy.Field()
    payor5_plan4 = scrapy.Field()
    payor5_plan5 = scrapy.Field()
    payor5_plan1 = scrapy.Field()
    payor6_plan2 = scrapy.Field()
    payor6_plan3 = scrapy.Field()
    payor6_plan4 = scrapy.Field()
    payor6_plan5 = scrapy.Field()
    payor6_plan1 = scrapy.Field()
    payor7_plan2 = scrapy.Field()
    payor7_plan3 = scrapy.Field()
    payor7_plan4 = scrapy.Field()
    payor7_plan5 = scrapy.Field()
    payor7_plan1 = scrapy.Field()
    payor8_plan2 = scrapy.Field()
    payor8_plan3 = scrapy.Field()
    payor8_plan4 = scrapy.Field()
    payor8_plan5 = scrapy.Field()
    payor8_plan1 = scrapy.Field()
    payor9_plan2 = scrapy.Field()
    payor9_plan3 = scrapy.Field()
    payor9_plan4 = scrapy.Field()
    payor9_plan5 = scrapy.Field()
    payor9_plan1 = scrapy.Field()
    payor10_plan2 = scrapy.Field()
    payor10_plan3 = scrapy.Field()
    payor10_plan4 = scrapy.Field()
    payor10_plan5 = scrapy.Field()
    payor10_plan1 = scrapy.Field()
